import Dexie, { type Table } from "dexie";

/*
 * Static information about each flood-risk zone.
 * This comes from GIS / DEM / land-use datasets.
 */
export interface FloodZone {
  id: string;
  name: string;

  latitude: number;
  longitude: number;

  elevation: number;
  slope: number;

  landUse: string;
  imperviousness: number;
}

/*
 * Historical / offline flood dataset.
 *
 * This is the main dataset that our ML model will use.
 * No physical sensor is required.
 */
export interface FloodObservation {
  id?: number;

  zoneId: string;
  timestamp: number;

  latitude: number;
  longitude: number;

  rainfall15min: number;
  rainfall1hr: number;
  rainfall3hr: number;

  waterLevel: number;

  elevation: number;
  slope: number;

  landUse: string;
  imperviousness: number;

  floodDepth: number;
  floodOccurrence: 0 | 1;
}

/*
 * Predictions generated by the ML model.
 */
export interface FloodPrediction {
  id?: number;

  zoneId: string;
  timestamp: number;

  probability: number;

  predictedDepth: number;

  risk: "LOW" | "MODERATE" | "HIGH" | "CRITICAL";

  forecastMinutes: number;
}

/*
 * Stores data that needs to be synchronized later
 * when internet becomes available.
 */
export interface SyncQueueItem {
  id?: number;

  type: "observation" | "prediction";

  timestamp: number;

  payload: string;

  synced: boolean;
}

class UrbanFloodDatabase extends Dexie {
  zones!: Table<FloodZone, string>;
  floodObservations!: Table<FloodObservation, number>;
  predictions!: Table<FloodPrediction, number>;
  syncQueue!: Table<SyncQueueItem, number>;

  constructor() {
    super("UrbanFloodDatabase");

    /*
     * Version 2:
     * We are upgrading the database from the initial
     * sensor-based test structure to our software-only
     * offline dataset structure.
     */
    this.version(2).stores({
      zones: "id, name",

      floodObservations: "++id, zoneId, timestamp, floodOccurrence",

      predictions: "++id, zoneId, timestamp, risk",

      syncQueue: "++id, type, timestamp, synced",
    });
  }
}

export const db = new UrbanFloodDatabase();
